# Generated by Django 2.2.3 on 2019-07-22 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vip', '0002_auto_20190722_1058'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VipPermissions',
            new_name='VipPermission',
        ),
    ]
