# Generated by Django 2.2.3 on 2019-07-22 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vip', '0003_auto_20190722_1058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vippermission',
            old_name='per_id',
            new_name='perm_id',
        ),
    ]
