# Generated by Django 2.2.3 on 2019-07-18 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Swiped',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(verbose_name='登陆者的id')),
                ('sid', models.IntegerField(verbose_name='被划过/被喜欢的人')),
                ('mark', models.CharField(choices=[('like', '喜欢'), ('dislike', '不喜欢'), ('superlike', '超级喜欢')], max_length=16, verbose_name='使用动作的标记')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='使用动作的时间')),
            ],
            options={
                'db_table': 'swiper',
            },
        ),
    ]
