# Generated by Django 2.2.3 on 2019-07-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(choices=[('gz', '广州'), ('bj', '北京'), ('sz', '深圳'), ('hz', '杭州'), ('cd', '成都'), ('sh', '上海')], default='gz', max_length=16),
        ),
    ]
