# Generated by Django 2.2.3 on 2019-07-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190716_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('gz', '广州'), ('bj', '北京'), ('sz', '深圳'), ('hz', '杭州'), ('cd', '成都'), ('sh', '上海')], default='gz', max_length=16, verbose_name='交友城市')),
                ('min_diatance', models.IntegerField(default=0, verbose_name='寻找的最小公里')),
                ('max_diatance', models.IntegerField(default=10, verbose_name='寻找的最大公里')),
                ('min_dating_age', models.IntegerField(default=18, verbose_name='匹配最小年龄')),
                ('max_dating_age', models.IntegerField(default=40, verbose_name='匹配最大年龄')),
                ('dating_sex', models.IntegerField(choices=[(0, '未知'), (1, '男'), (2, '女')], default=0, verbose_name='喜好的性别')),
                ('auto_play', models.BooleanField(default=True, verbose_name='小动画')),
            ],
            options={
                'db_table': 'profiles',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(max_length=256, verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_day',
            field=models.IntegerField(default=1, verbose_name='出生日'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_month',
            field=models.IntegerField(default=1, verbose_name='出生月'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_year',
            field=models.IntegerField(default=2000, verbose_name='出生年'),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(choices=[('gz', '广州'), ('bj', '北京'), ('sz', '深圳'), ('hz', '杭州'), ('cd', '成都'), ('sh', '上海')], default='gz', max_length=16, verbose_name='你的城市'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=20, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phonenum',
            field=models.CharField(max_length=32, unique=True, verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.IntegerField(choices=[(0, '未知'), (1, '男'), (2, '女')], default=0, verbose_name='性别'),
        ),
    ]
